### ISSUE TITLE
The home page should only display a Welcome message

### ISSUE THREAD

**Issue by KatheVRM** [mauricioZelaya/bug-validation-site#10]
**ID.** KV-001
**Severity.**
Trivial - 1
**Description.**
On the home page, the title, subtitle and description should be removed, in addition to the "learn more" button, replace the previous three with a welcome message such as "Welcome to my page" and delete the button mentioned.
**Requirements.**
-Have internet connection
-Been able to load the page: https://qa-bugs-hunting-demo-site.herokuapp.com/
**Steps.**
1.- Open the page: https://qa-bugs-hunting-demo-site.herokuapp.com/
2.-Read and look the home page 
**Actual results:**
When you enter the home page you can see a title, subtitle and description as well as a "learn more" button.
**Expected result.**
On the start page there should only be a welcome message like “ Welcome to my page”

**Comment by mauricioZelaya** [comment]
According last meeting with PO , this button will not be part of the design
