### ISSUE TITLE
the User List menu does not display any user records

### ISSUE THREAD

**Issue by arielinfs** [mauricioZelaya/bug-validation-site#12]
Severity: Major

Description: 
when a new user is registered it is not shown in the User list page

Requeriments: 
1.- `access to https://qa-bugs-hunting-demo-site.herokuapp.com/`

Step:
1.-Enter to the link on the web page of the requirements
`2. go to 'ad-user' link`
2. `add all the required information and` register a new user
3.-go to user List `page` (click on 'list users' menu)
4.-Notice that when a new user is registered it is not displayed in the User list page

Actual result:
dont displayed any user en la user List page

Expected result:
the User List menu should be displayed user records

**Comment by mauricioZelaya** [comment]
table of users is already fixed and now it is being displayed
