### ISSUE TITLE
The website must be totally in English

### ISSUE THREAD

**Issue by KatheVRM** [mauricioZelaya/bug-validation-site#13]
**ID.** KV-002
**Severity.**
Medium - 3
**Description.**
On the home page there are texts in Spanish and English
**Note 1.**.- All the language of the home page and the labels must be in English
**Requirements.**
-Have internet connection
-Been able to load the page: https://qa-bugs-hunting-demo-site.herokuapp.com/
**Steps.**
1.- Open the page: https://qa-bugs-hunting-demo-site.herokuapp.com/
2.-Read and look the home page 
**Actual results:**
When you enter the home page you can read texts in Spanish and English.
**Expected result.**
All the language of the home page and the labels must be in English.

**Comment by mauricioZelaya** [comment]
Language issues has been fixed
