### ISSUE TITLE
There are  spelling errors in the welcome description on the home page

### ISSUE THREAD

**Issue by claryy** [mauricioZelaya/bug-validation-site#14]
**ID:** CSOLANO -001
**Severity:** 1
**Description:** 
When a user goes to the main page a descriptive message of the page is displayed with some spelling errors like TBienvenidos and citio

**Requirements**

- Have access to link: https://qa-bugs-hunting-demo-site.herokuapp.com

**Steps:**
Go to https://qa-bugs-hunting-demo-site.herokuapp.com
Notice that a descriptive and welcome to the site message is displayed with some spelling errors

**Actual Result:**
spelling errors are being observed in the  welcome message to the home page.

**Expected Result:**
The home page should have no spelling errors

**Comment by mauricioZelaya** [comment]
Language issues were fixed in the last deployed site
