### ISSUE TITLE
The "Phone" box requires that it be completed with an email format.

### ISSUE THREAD

**Issue by ALeidaCarla** [mauricioZelaya/bug-validation-site#15]
**ID:**AECV-001
**Severity:**5 
**Description:**
When the user writes in any format that does not have the @ symbol, it is not validated.
note 1: 
the box shows a comment where it presents the required format
**Requirements:**
have access to add user https://qa-bugs-hunting-demo-site.herokuapp.com
**Steps**
1. enter to link https://qa-bugs-hunting-demo-site.herokuapp.com
2. fill the "phone" box
3. press the botton "Sign up"
4. notice that the box shows a comment where it presents the required format.
**Actual Result**
The user writes in any format that does not have the @ symbol, it is not validated.
**Expected Result**
The user should be able to enter their phone number and this should validate it.

**Additional Information**
![image](https://user-images.githubusercontent.com/28932391/85484855-a61e9c80-b595-11ea-899c-9fde33bc4246.png)

**Comment by mauricioZelaya** [comment]
email validation was removed from phone field
