### ISSUE TITLE
En el text field "Last Name" muestra el texto codificado

### ISSUE THREAD

**Issue by Estephany17** [mauricioZelaya/bug-validation-site#16]
**ID:**  NEVA-001

**Severity:** 
Major

**Description:** 
Cuando quiero ingresar el apellido en el text field "Last Name", se muestra el texto que uno escribe, codificado

**Requirements:**
- tener conexion a internet
- cargar la pagina

**Steps:**
1. Ingresar al sitio qa-bugs-hunting-demo-site.herokuapp.com
2. click en el Boton "Add Users"
3. Escribir en el text field "Last Name"

**Actual Result:**
Al ingresar el apellido en el text field "Last Name", se muestra el texto que uno escribe, codificado (como password)

**Expected Result:**
Al ingresar el apellido en el text field "Last Name", se debe mostrar el texto que uno escribe

**Additional Information:**
![Flask Web App - Google Chrome 6_23_2020 9_38_01 PM](https://user-images.githubusercontent.com/66704587/85487117-f697f900-b599-11ea-8bda-c266065a69f2.png)

**Comment by mauricioZelaya** [comment]
el tipo de campo para 'last name' ha sido cambiado  y ahora es de tipo text field
