### ISSUE TITLE
When entering an email without .com the application generates an internal server error

### ISSUE THREAD

**Issue by KatheVRM** [mauricioZelaya/bug-validation-site#17]
**ID.** KV-003
**Severity.**
Major - 4
**Description.**
In the e-mail field, when an email is entered without the .com characters, the system leads to an internal server error
**Note 1.**.- Testing was limited to emails without a valid extension
**Requirements.**
-Been able to load the page: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user 
**Steps.**
1.- Open the page: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user 
2.- Enter an email without .com
**Actual results:**
When an email is entered without .com the page throws an internal server error
**Expected result.**
When a user does not enter their email correctly, the system should send an appropriate warning message

**Comment by mauricioZelaya** [comment]
I am not able to reproduce this issue
