### ISSUE TITLE
The "Last Name" textbox on the "Add Users" page does not validate the textbox

### ISSUE THREAD

**Issue by valeria1208** [mauricioZelaya/bug-validation-site#19]
**The "Last Name" textbox on the "Add Users" page does not validate the textbox**
**ID:** FERNANDEZ-001
**SEVERITY:** 4

**DESCRIPTION:**
when you write numbers or simbols in the textbox "Last Name", it doesn´t appear an error message.

**REQUIREMENTS:**
1.- Have internet access
2.- Access to a web browser
2.- Acces to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user

**STEPS:**
1.- Enter to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user
2.- Write in the textbox "Name": "Nombre"
2.- Write in the textbox "Last Name": "abc123@"
3.- Press the button "Sign in"
4.- Notice that the message "contacto agregado satisfactoriamente!!!" appears and the textbox "Last Name" isn´t validate

**ACTUAL RESULT:**
The "Last Name" textbox on the "Add Users" page does not validate what is written in the textbox

**EXPECTED RESULT:**
The "Last Name" textbox on the "Add Users" page should validate the textbox "Last Name" and should´t permit to write numbers or other simbols.

**Comment by mauricioZelaya** [comment]
is this not a bug due to internacionalization, in different idioms it will be possible to add some symbols in name or last name
