### ISSUE TITLE
The "Name" textbox on the "Add Users" page does not validate the textbox

### ISSUE THREAD

**Issue by valeria1208** [mauricioZelaya/bug-validation-site#20]
**The "Name" textbox on the "Add Users" page does not validate the textbox**
**ID:** FERNANDEZ-002
**SEVERITY:** 4

**DESCRIPTION:**
when you write numbers or simbols in the textbox "Name", it doesn´t appear an error message.

**REQUIREMENTS:**
1.- Have internet access
2.- Access to a web browser
2.- Acces to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user

**STEPS:**
1.- Enter to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user
2.- Write in the textbox "Name": "Nombre123@"
3.- Press the button "Sign in"
4.- Notice that the message "contacto agregado satisfactoriamente!!!" appears and the textbox "Name" isn´t validate

**ACTUAL RESULT:**
The "Name" textbox on the "Add Users" page does not validate what is written in the textbox

**EXPECTED RESULT:**
The "Name" textbox on the "Add Users" page should´t permit to write numbers or other simbols.

**Comment by mauricioZelaya** [comment]
let's review internationalization with the PO
