### ISSUE TITLE
 the button "Learn more" does not perform any action

### ISSUE THREAD

**Issue by valeria1208** [mauricioZelaya/bug-validation-site#7]
*SEVERITY:* 3

*DESCRIPTION:*
when pressing the button, no action is perform

*REQUIREMENTS:*
1.- Enter to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/

*STEPS:*
1.- Enter to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/
2.- Press the button "Learn more"
3.- Notice that when when pressing the button, no action is perform

*ACTUAL RESULT:*
 the button "Learn more" does not perform any action

*EXPECTED RESULT:* 
the button should redirect you to another page or do another action

**Comment by mauricioZelaya** [comment]
According the PO requirements, this button won't be part of the design in this sprint
you can close this ticket

**Comment by mauricioZelaya** [comment]
**title:** "the button "Learn more" does not perform any action" Validation 
**environment:** QA
**branch:** 'adding_edit-and-delete-page-mock'
**estimation:** 10 min
**points to review**
- [x] Validate no "learn more" button is displayed going to https://qa-bugs-hunting-demo-site.herokuapp.com/
- [x] Validate that home link is going to https://qa-bugs-hunting-demo-site.herokuapp.com/ and no 'learn more' button is displayed
- [x] Validate that 'Bug Validation Course' link is going to https://qa-bugs-hunting-demo-site.herokuapp.com/ and no 'learn more' button is displayed

![image](https://user-images.githubusercontent.com/28932391/85638719-a6ca3800-b654-11ea-9b2c-28b15a8b46a1.png)

**note** Inspecting the code in the browser we noticed that button is only commented and not removed
![image](https://user-images.githubusercontent.com/28932391/85639052-96668d00-b655-11ea-8d56-08779b6519b6.png)
