### ISSUE TITLE
 The "Last Name" textbox on the "Add Users" page does not display the typed text

### ISSUE THREAD

**Issue by valeria1208** [mauricioZelaya/bug-validation-site#8]
*SEVERITY:* 4

*DESCRIPTION:*
when you write in the textbox "Last Name", you can not see what is written since dots appear instead of letters

*REQUIREMENTS:*
1.- Enter to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user

*STEPS:*
1.- Enter to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user
2.- Write in the textbox "Last Name"
3.- Notice that when you write, appears dots instead of letters

*ACTUAL RESULT:*
 The "Last Name" textbox on the "Add Users" page does not display the typed text

*EXPECTED RESULT:* 
 The "Last Name" textbox on the "Add Users" page display what is written

**Comment by mauricioZelaya** [comment]
field type was changed and now is only a text field

**Comment by valeria1208** [comment]
**The "Last Name" textbox on the "Add Users" page does not validate the textbox**
ID: FERNANDEZ-001
SEVERITY: 4

DESCRIPTION:
when you write numbers or simbols in the textbox "Last Name", it doesn´t appear an error message.

REQUIREMENTS:
1.- Have internet access
2.- Access to a web browser
2.- Acces to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user

STEPS:
1.- Enter to the link: https://qa-bugs-hunting-demo-site.herokuapp.com/add-user
2.- Write in the textbox "Name": "Nombre"
2.- Write in the textbox "Last Name": "abc123@"
3.- Press the button "Sign in"
4.- Notice that the message "contacto agregado satisfactoriamente!!!" appears and the textbox "Last Name" isn´t validate

ACTUAL RESULT:
The "Last Name" textbox on the "Add Users" page does not validate what is written in the textbox

EXPECTED RESULT:
The "Last Name" textbox on the "Add Users" page should validate the textbox "Last Name" and should´t permit to write numbers or other simbols.

**Comment by mauricioZelaya** [comment]
**title** "The "Last Name" textbox on the "Add Users" page does not display the typed text" validation
**environment** QA
**branch:** adding_edit-and-delete-page-mock
**estimation:**
**points to review:**
- [x] validate that 'last name' filed is displaying the last name that is being written (acceptance TC)
![image](https://user-images.githubusercontent.com/28932391/85641297-227bb300-b65c-11ea-8a73-635dd0d40919.png)

- [ ] validate that 'last name' text box is validating special characters (test around TC)
![image](https://user-images.githubusercontent.com/28932391/85641420-84d4b380-b65c-11ea-91ee-eb514bcc8474.png)
**Failed** it is possible to add a last name with special characters

- [ ] validate that 'last name' is a required field (test around TC)
![image](https://user-images.githubusercontent.com/28932391/85641560-e9900e00-b65c-11ea-9397-4dde573bebfa.png)
**failed** is possible add anew user without a last name / last name is not being validated as required field

- [ ]  validate that 'last name' length is up to 23 characters (by standard) (test around TC)
![image](https://user-images.githubusercontent.com/28932391/85641678-586d6700-b65d-11ea-93f8-8f7f07d05f60.png)
**failed** last name is accepting more than 23 characters

- [x] validate that an user with valid information is saved (acceptance TC)
![image](https://user-images.githubusercontent.com/28932391/85641256-07a93e80-b65c-11ea-9e9e-67b159747062.png)
